inherit_from: .rubocop_u2i.yml

Rails:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - spec/spec_helper.rb
    - vendor/**/*

Metrics/LineLength:
  Max: 80
  Enabled: true
  Exclude:
    - spec/**/*
